type: object
description: |
  This is data that is linked to products data quality
properties:
  data_quality_bugs_tags:
    type: array
    items:
      type: object
  data_quality_errors_tags:
    type: array
    items:
      type: object
  data_quality_info_tags:
    type: array
    items:
      type: string
  data_quality_tags:
    type: array
    items:
      type: string
  data_quality_warning_tags:
    type: array
    items:
      type: string
  data_quality_warnings_tags:
    type: array
    items:
      type: string
  data_sources:
    type: string
    description: |
      Source of data imported from producers.
  data_sources_tags:
    type: array
    items:
      type: string
  debug_param_sorted_langs:
    type: array
    items:
      type: string
  last_check_dates_tags:
    type: array
    items:
      type: string
  last_checked_t:
    type: integer
  last_checker:
    type: string

  states:
    description: |
      comma separated list of values indicating some states of the product,
      like things to be done, or to be completed.
      See [states taxonomy](https://static.openfoodfacts.net/data/taxonomies/states.json)
    type: string
    examples:
      - "en:to-be-completed, en:nutrition-facts-completed, en:ingredients-to-be-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:origins-to-be-completed, en:categories-completed, en:brands-completed, en:packaging-to-be-completed, en:quantity-completed, en:product-name-completed, en:photos-to-be-validated, en:packaging-photo-to-be-selected, en:nutrition-photo-selected, en:ingredients-photo-selected, en:front-photo-selected, en:photos-uploaded"
  states_hierarchy:
    type: array
    items:
      type: string
    examples:
      - - "en:to-be-completed"
        - "en:nutrition-facts-completed"
        - "en:ingredients-to-be-completed"
        - "en:expiration-date-to-be-completed"
        - "en:packaging-code-to-be-completed"
        - "en:characteristics-to-be-completed"
        - "en:origins-to-be-completed"
        - "en:categories-completed"
        - "en:brands-completed"
        - "en:packaging-to-be-completed"
        - "en:quantity-completed"
        - "en:product-name-completed"
        - "en:photos-to-be-validated"
        - "en:packaging-photo-to-be-selected"
        - "en:nutrition-photo-selected"
        - "en:ingredients-photo-selected"
        - "en:front-photo-selected"
        - "en:photos-uploaded"
  states_tags:
    type: array
    items:
      description: |
        Each state describe something that is completed or is to be done or improved on the product.

        Refer to [states taxonomy](https://static.openfoodfacts.net/data/taxonomies/states.json)
      type: string

  misc_tags:
    description: |
      Information about different aspect of the product
    type: array
    items:
      type: string
