type: object
description: |
  This is data that is linked to products data quality
properties:
  data_quality_bugs_tags:
    type: array
    items:
      type: string
      description: |
        Each data quality bug describes a data quality bug on the product.

        Refer to the [data quality taxonomy](https://static.openfoodfacts.org/data/taxonomies/data_quality.json)
  data_quality_completeness_tags:
    type: array
    items:
      type: string
  data_quality_dimensions:
    type: object
    properties:
      accuracy:
        type: object
        properties:
          overall:
            type: string
      completeness:
        type: object
        properties:
          overall:
            type: string
            description: |
              The overall quality score of the product data, calculated as a weighted average of completeness, correctness, and informativeness.
          general_information:
            type: string
          ingredients:
            type: string
          nutrition:
            type: string
          packaging:
            type: string
  data_quality_errors_tags:
    type: array
    items:
      type: string
      description: |
        Each Data Quality Error describes a data quality error on the product.

        Refer to the [data quality taxonomy](https://static.openfoodfacts.org/data/taxonomies/data_quality.json)
  data_quality_info_tags:
    type: array
    items:
      type: string
      description: |
        Each Data Quality Info describes a data quality info on the product.

        Refer to the [data quality taxonomy](https://static.openfoodfacts.org/data/taxonomies/data_quality.json)
  data_quality_tags:
    type: array
    items:
      type: string
  data_quality_warnings_tags:
    type: array
    items:
      type: string
      description: |
        Each Data Quality warning tag describes a data quality warning on the product.

        Refer to the [data quality taxonomy](https://static.openfoodfacts.org/data/taxonomies/data_quality.json)
  data_sources:
    type: string
    description: |
      Source of data imported from producers.
  data_sources_tags:
    type: array
    items:
      type: string
  debug_param_sorted_langs:
    type: array
    items:
      type: string
  last_check_dates_tags:
    type: array
    items:
      type: string
  last_checked_t:
    type: integer
  last_checker:
    type: string

  states:
    description: |
      comma separated list of values indicating some states of the product,
      like things to be done, or to be completed.
      See [states taxonomy](https://static.openfoodfacts.net/data/taxonomies/states.json)
    type: string
    examples:
      - "en:to-be-completed, en:nutrition-facts-completed, en:ingredients-to-be-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:origins-to-be-completed, en:categories-completed, en:brands-completed, en:packaging-to-be-completed, en:quantity-completed, en:product-name-completed, en:photos-to-be-validated, en:packaging-photo-to-be-selected, en:nutrition-photo-selected, en:ingredients-photo-selected, en:front-photo-selected, en:photos-uploaded"
  states_hierarchy:
    type: array
    items:
      type: string
    examples:
      - - "en:to-be-completed"
        - "en:nutrition-facts-completed"
        - "en:ingredients-to-be-completed"
        - "en:expiration-date-to-be-completed"
        - "en:packaging-code-to-be-completed"
        - "en:characteristics-to-be-completed"
        - "en:origins-to-be-completed"
        - "en:categories-completed"
        - "en:brands-completed"
        - "en:packaging-to-be-completed"
        - "en:quantity-completed"
        - "en:product-name-completed"
        - "en:photos-to-be-validated"
        - "en:packaging-photo-to-be-selected"
        - "en:nutrition-photo-selected"
        - "en:ingredients-photo-selected"
        - "en:front-photo-selected"
        - "en:photos-uploaded"
  states_tags:
    type: array
    items:
      description: |
        Each state describe something that is completed or is to be done or improved on the product.

        Refer to [states taxonomy](https://static.openfoodfacts.net/data/taxonomies/states.json)
      type: string

  misc_tags:
    description: |
      Information about different aspect of the product
        Refer to [misc taxonomy](https://static.openfoodfacts.org/data/taxonomies/misc.json)
    type: array
    items:
      type: string
